// data.js — Your full tempered glass data array

const temperedGlassData = [
  {
    mainModel: "MI A3",
    models: ["MI A3", "OPPO A1K", "REALME C2"],
  },
  {
    mainModel: "MI NOTE8",
    models: ["MI NOTE8"],
  },
  {
    mainModel: "VIVO Y91",
    models: [
      "VIVO Y90",
      "VIVO Y91",
      "VIVO Y93",
      "VIVO Y93S",
      "VIVIO Y95",
      "VIVO Y1S",
      "OPPO A7",
      "OPPO A7X",
      "OPPO A12",
      "OPPO 11K",
      "OPPO A5S",
      "REALME 3",
      "SAMSUNG A10",
      "SAMSUNG A10S",
      "SAMSUNG M10",
      "SAMSUNG M01S",
      "SAMSUNG M20",
      "OPPO A11K",
    ],
  },
  {
    mainModel: "VIVO S1",
    models: [
      "SAMSUNG A30",
      "SAMSUNG A50",
      "SAMSUNG M30",
      "SAMSUNG A40S",
      "SAMSUNG A50S",
      "SAMSUNG A20",
      "SAMSUNG M30S",
      "SAMSUNG M10S",
      "SAMSUNGA30S",
      "SAMSUNG M21",
      "SAMSUNG M31",
      "SAMSUNG F41",
      "VIVO U10",
      "VIVO Y9S",
      "VIVO Z1X",
      "VIVO Z5",
      "VIVO V21",
      "VIVO V21E4G",
      "IQOO NEO",
      "IQOO PRO",
      "VIVO S1",
      "VIVO S1PRO",
      "SAMSUNGM21S",
    ],
  },
  {
    mainModel: "MI NOTE8PRO",
    models: [
      "MI NOTE8PRO",
      "MI NOTE9T",
      "MI NOTE94G",
      "MI 9POWER",
      "POCO M3",
      "OPPO F11",
      "OPPO A9",
      "OPPO RENOACE",
      "REALME X2PRO",
      "VIVO U20",
      "VIVO Y19",
      "ONEPLUS 7T",
    ],
  },
  {
    mainModel: "MI NOTE7",
    models: ["MI NOTE7", "MI NOTE7S", "MI NOTE7PRO"],
  },
  {
    mainModel: "VIVO Y12",
    models: [
      "VIVO Y3",
      "VIVO Y11",
      "VIVO Y12",
      "VIVO Y15",
      "VIVO Y17",
      "VIVO U10",
    ],
  },
  {
    mainModel: "SAMSUNG A14",
    models: ["SAMSUNG A14", "SAMSUNG M14", "SAMSUNG F14"],
  },
  {
    mainModel: "SAMSUNG A34",
    models: ["SAMSUNG A34"],
  },
  {
    mainModel: "MI 7",
    models: ["MI Y3", "MI 7"],
  },
  {
    mainModel: "MI 8",
    models: ["MI 8", "MI 8A", "MI 8ADUAL"],
  },
  {
    mainModel: "ONEPLUS 5",
    models: ["ONEPLUS 5"],
  },
  {
    mainModel: "ONEPLUS 5T",
    models: ["ONEPLUS 5T"],
  },
  {
    mainModel: "ONEPLUS 6",
    models: ["ONEPLUS 6"],
  },
  {
    mainModel: "SASMUNG A31",
    models: [
      "SAMSUNG A31",
      "SAMSUNG M32",
      "SAMSUNG M22",
      "SAMSUNG F22",
      "SAMSUNG A224G",
      "SAMSUNG A324G",
      "SAMSUNG A33",
      "VIVO Y100",
      "VIVO T2",
      "IQOO Z7",
      "IQOO Z7S",
    ],
  },
  {
    mainModel: "VIVO V20",
    models: [
      "OPPO A91",
      "OPPO F17",
      "OPPO A73",
      "OPPO F15",
      "OPPO RENO3",
      "VIVO T1",
      "VIVO T144W",
      "IQOO Z644W",
      "VIVO V20",
      "VIVO V20SE",
      "VIVO V21E",
      "VIVO V21E5G",
      "VIVO V23E",
      "VIVO Y73",
      "VIVO Y73S",
      "VIVO Y754G",
    ],
  },
  {
    mainModel: "VIOV V11PRO",
    models: [
      "REALME X2",
      "REALME XT",
      "VIVO V11PRO",
      "VIVO Z3",
      "IQOO",
    ],
  },
  {
    mainModel: "REALME 10PRO",
    models: ["REALME 10PRO"],
  },
  {
    mainModel: "REALME 5",
    models: [
      "VIVO Y01",
      "VIVO Y02",
      "VIVO Y02A",
      "VIVO YO2S",
      "VIVO Y02T",
      "VIVO Y3S",
      "VIVO Y11S",
      "VIVO Y12S",
      "VIVO Y12A",
      "VIVO Y15S",
      "VIVO Y16",
      "VIVO Y17S",
      "VIVOP Y18",
      "VIVO Y20",
      "VIVO Y20I",
      "VIVO Y20G",
      "VIVO Y20A",
      "VIVO Y21A",
      "VIVO Y21S",
      "VIVO Y21T",
      "VIVO Y21",
      "VIVO Y21G",
      "VIVO Y22",
      "VIVO Y22S",
      "VIVO Y28S",
      "VIVO Y285G",
      "VIVO Y305G",
      "VIVO Y30",
      "VIVO Y31",
      "VIVO Y32",
      "VIVO Y31S5G",
      "VIVO Y33S5G",
      "VIVO Y33",
      "VIVO Y33S",
      "VIVO Y33T",
      "VIVO Y36",
      "VIVO Y36I ",
      "VIVO Y56",
      "VIVO Y51A",
      "VIVO Y51",
      "VIVO Y525G",
      "VIVO Y52S",
      "VIVO Y53S",
      "VIVO Y55S5G",
      "VIVO Y725G",
      "VIVO Y755G",
      "VIVO Y765G",
      "VIVO Y285G",
      "VIVO Y76S5G",
      "VIVO Y775G",
      "VIVO T15G",
      "VIVO T1X",
      "VIVO T1X4G",
      "VIVO T2X",
      "IQOO Z3",
      "IQOO Z5X",
      "IQOO Z6",
      "IQOO Z6X",
      "POCO M45G",
      "POCO M5",
      "MI 105G",
      "MI 11PRIME5G",
      "SAMSUNG A12",
      "SMASNUNG A02",
      "SAMSUNG A02S",
      "SAMSUNG A025G",
      "SAMSUNG A03",
      "SAMSUNG A03S",
      "SAMSUNG A03CORE",
      "SAMSUNG AO4",
      "SAMSUNG A04S",
      "SAMSUNGA04CORE",
      "SAMSUNG A04E",
      "SAMSUNG A13",
      "SAMSUNGA23",
      "SAMSUN A325G",
      "SAMSUNG M02",
      "SAMSUNG M02S",
      "SAMSUNG M04",
      "SAMSUNG M12",
      "SAMSUNG M13",
      "SAMSUNG M23",
      "SAMSUNG M32",
      "SAMSUNG M33",
      "SAMSUNG F02S",
      "SAMSUNG F04",
      "SAMSUNG F12",
      "SAMSUNG F13",
      "SAMSUNG F23",
      "MI 9A",
      "MI 9C",
      "MI 9I",
      "MI 9 ACTIVE",
      "POCO C3",
      "POCO C31",
      "REALME 5",
      "REALME 5I",
      "REALME C3",
      "REALME C11",
      "REALME C12",
      "REALME C15",
      "REALME C20",
      "REALME C21",
      "REALME C21Y",
      "REALME C25",
      "REALME C25Y",
      "REALME C25S",
      "REALME C30",
      "REALME C31",
      "REALME C33",
      "REALME C35",
      "REALME NARZO10",
      "REALME NARZO10A",
      "REALME NARZO20",
      "REALME NARZO20A",
      "REALME NARZO30A",
      "REALME NARZO50A",
      "REALME NARZO50APRIME",
      "REALME NARZO50I",
      "REALME NARZO50IPRIME",
      "OPPO A52020",
      "OPPO A92020",
      "OPPO A11",
      "OPPO A15",
      "OPPO A15S",
      "OPPO A16",
      "OPPO A16E",
      "OPPO A16K",
      "OPPO A17",
      "OPPO A17K",
      "OPPO A18",
      "OPPO A31",
      "OPPO A35",
      "OPPO A38",
      "OPPO A53S5G",
      "OPPO A54S",
      "OPPO A555G",
      "OPPO A565G",
      "OPPO A57",
      "OPPO A57S",
      "OPPO A57E",
      "OPPO A59",
      "OPPO A77",
      "OPPO A77S",
      "OPPO A785G",
      "OPPO K105G",
    ],
  },
  {
    mainModel: "VIVO V23",
    models: ["VIVO V23", "VIVO V20PRO"],
  },
  {
    mainModel: "OPPO A5",
    models: ["OPPO A5", "OPPO A3S", "REALME 2", "REALME C1", "VIVO V9"],
  },
  {
    mainModel: "OPPO F9",
    models: [
      "REALME 3PRO",
      "OPPO F9",
      "REALME 2PRO",
      "OPPO F9PRO",
      "REALME U1",
      "REALME 5PRO",
    ],
  },
  {
    mainModel: "IPHONE 12PROMAX",
    models: ["IPHONE 12PROMAX"],
  },
  {
    mainModel: "IPHONE 15",
    models: ["IPHONE15", "IPHONE 16"],
  },
  {
    mainModel: "IPHONE 11PROMAX",
    models: ["IPHONE 11PROMAX", "IPHONE XSMAX"],
  },
  {
    mainModel: "IPHONE 7PLUS",
    models: ["IPHONE 7PLUS", "IPHONE 8PLUS"],
  },
  {
    mainModel: "IPHONE 13MINI",
    models: ["IPHONE 13MINI"],
  },
  {
    mainModel: "IPHONE 7",
    models: ["IPHONE", "IPHONE 8", "IPHONE SE"],
  },
  {
    mainModel: "IPHONE X",
    models: ["IPHONE X", "IPHONE XS", "IPHONE 11PRO"],
  },
  {
    mainModel: "IPHONE 6PLUS",
    models: ["IPHONE 6PLUS"],
  },
  {
    mainModel: "IPHOME 11",
    models: ["IPHONE 11", "IPHONE XR"],
  },
  {
    mainModel: "IPHONE 13",
    models: ["IPHONE 13", "IPHONE 14", "IPHONE 13PRO"],
  },
  {
    mainModel: "IPHONE 12",
    models: ["IPHONE 12", "IPHONE 12PRO"],
  },
  {
    mainModel: "IPHONE 15PLUS",
    models: ["IPHONE 15PLUS", "IPHONE 16PLUS"],
  },
  {
    mainModel: "IPHONE 14PLUS",
    models: ["IPHONE 14PLUS", "IPHONE 13PROMAX"],
  },
  {
    mainModel: "IPHONE 15PROMAX",
    models: ["IPHONE 15PROMAX"],
  },
  {
    mainModel: "IPHONE 14PRO",
    models: ["IPHONE 14PRO"],
  },
  {
    mainModel: "IPHONE 15PRO",
    models: ["IPHONE 15PRO"],
  },
  {
    mainModel: "MI NOTE115G",
    models: ["MI NOTE115G", "MI NOTE11T5G", "MI NOTE11S5G", "POCO M4PRO5G"],
  },
  {
    mainModel: "MI NOTE10S",
    models: [
      "MI NOTE12S",
      "MI NOTE11S",
      "MI NOTE10S",
      "MI NOTE104G",
      "POCO M4PRO4G",
      "POCO M5S",
    ],
  },
  {
    mainModel: "REALME 6",
    models: [
      "OPPO RENO2Z",
      "OPPO RENO2F",
      "OPPO RENO2F",
      "OPPO A52",
      "OPPO A72",
      "OPPO A92",
      "OPPO A535G",
      "OPPO A545G",
      "OPPO A725G",
      "OPPO A735G",
      "OPPO A745G",
      "OPPO A935G",
      "REALME 6",
      "REALME 6S",
      "REALME 75G",
      "REALME 85G",
      "REALME X7PRO",
      "REALME NARZO",
      "REALME NARZO20PRO",
      "REALME NARZO305G",
      "REALME NARZO30PRO5G",
      "REDMI 10",
      "MI 10",
      "MI 10PRIME",
      "MI NOTE105G",
      "MI NOTE10T",
      "POCO M3PRO",
      "OPPO A93S",
      "REALME 8S5G",
    ],
  },
  {
    mainModel: "VIVO V17",
    models: [
      "VIVO V17PRO",
      "VIVO IQOO3",
      "OPPO RENO3PRO",
      "OPPO RENO5",
      "ONEPLUS NORD2",
      "ONEPLUS NORDCE",
      "REALME X50PRO",
    ],
  },
  {
    mainModel: "VIVO V15PRO",
    models: ["VIVO V15PRO", "MI K20", "MI K20PRO", "SAMSUNG S21FE"],
  },
  {
    mainModel: "ONEPLUS NORD",
    models: [
      "ONEPLUS NORD",
      "ONEPLUS NORD2T",
      "OPPO RENO6",
      "REALME GT",
      "REALME GTMASTER",
      "REALME GTNEO2T",
      "REALME GTNEO",
      "REALME X7MAX",
      "OPPO RENO7",
    ],
  },
  {
    mainModel: "SAMSUNG A51",
    models: [
      "SMASUNG A51",
      "SAMSUBNG A52",
      "SAMSUNG A52S",
      "SAMSUNG A535G",
      "SAMSUNG M31S",
      "SAMSUNG S20FE",
      "OPPO F17PRO",
      "OPPO RENO4",
      "OPPO RENO 5",
    ],
  },
  {
    mainModel: "OPPO F19",
    models: [
      "OPPO F19",
      "OPPO F19PRO",
      "OPPO F19PROPLUS",
      "OPPO F21PRO",
      "OPPO F21SPRO",
      "OPPO A744G",
      "OPPO A784G",
      "OPPO A94",
      "OPPO A95",
      "OPPO A96",
      "OPPO RENO8",
      "REALME 84G",
      "REALME 8PRO4G",
      "REALME 94G",
      "REALME 9PROPLUS",
      "REALME X7",
      "REALME 7PRO",
      "VIVO V155G",
      "REALME NARZO605G",
      "REALME NARZO50PRO",
      "ONEPLUS NORDCE2",
      "OPPO F19S",
      "REALME 85G",
      "REALME 8LITE",
    ],
  },
  {
    mainModel: "ONEPLUS NORDCE2LITE",
    models: [
      "OPPO K10",
      "OPPO A53",
      "OPPO A53S",
      "OPPO A54",
      "OPPO A554G",
      "OPPO A76",
      "OPPO A92S",
      "REALME 6PRO",
      "REALME 6I",
      "REALME 7I",
      "REALME 8I",
      "REALME 9I",
      "REALME 9PRO",
      "REALME 95G",
      "REALME 95GSPEED",
      "REALME 5GSE",
      "REALME NARZO50",
      "ONEPLUS NORDCE2LITE",
      "SAMSUNG F52",
      "SAMSUNG A21",
      "SAMSUNG A21S",
      "OPPO A11S",
      "OPPO A324G",
      "OPPO A33",
      "OPPO A36",
      "",
    ],
  },
  {
    mainModel: "ONEPLUS NORD3",
    models: [
      "ONEPLUS NORD3",
      "ONEPLUS NORDCE3",
      "ONEPLUS NORDCE4",
      "VIVO T2",
      "VIVO T3",
      "VIVO Y200",
      "VIVO Y200E",
      "IQOO Z9",
      "IQOO NEO6",
      "OPPO K11",
      "REALME P1",
      "REALME GT5",
      "REALME 12PLUS",
      "REALME 12X",
      "REALME NARZO70PRO",
      "OPPO F27",
      "REALME NARZO70",
      "OPPO RENO12F",
    ],
  },
  {
    mainModel: "MI NOTE9PRO",
    models: [
      "MI K30",
      "MI K30PRO",
      "MI NOTE9PRO",
      "MI NOTE9PROMAX",
      "MI 10I",
      "MI 10T",
      "MI 10LITE",
      "MI 10TPRO",
      "POCO X2",
      "POCO X3",
      "POCO X3PRO",
      "POCO M2PRO",
      "MI 11T",
      "MI 11TPRO",
      "VIVO Y27S",
      "VIVO Y36",
      "IQOO Z5",
      "IQOO Z6",
      "IQOO Z7",
      "IQOO Z7X",
      "IQOO NEO5",
      "IQOO NEO10",
      "REALME GT3",
      "SAMSUNG A72",
      "SAMSUNG M55",
      "SAMSUNG F55",
      "SAMSUNG M55S",
      "SAMSUNG A80",
      "SAMSUNG A90",
      "SAMSUNG C55",
    ],
  },
  {
    mainModel: "OPPO F11PRO",
    models: [
      "OPPO F11PRO",
      "OPPO K3",
      "REALME X",
      "VIVO Z1PRO",
      "VIVO Y30",
      "VIVO Y50",
      "VIVO V15",
      "MI NOTE9",
      "VIVO Z5X",
      "MI NOTEE9T",
      "SAMSUNG A11",
      "SAMSUNG M11",
    ],
  },
  {
    mainModel: "SAMSUNG J7PRO",
    models: ["SAMSUNG J7PRO"],
  },
  {
    mainModel: "MI NOTE4",
    models: ["MI NOTE4"],
  },
  {
    mainModel: "SAMSUNG J7PRIME",
    models: ["SMASUNG J7PRIME"],
  },
  {
    mainModel: "MI Y2",
    models: ["MI Y2", "MI S2"],
  },
  {
    mainModel: "MI NOTE5",
    models: ["MI NOTE5", "MI ONTE5PLUS"],
  },
  {
    mainModel: "SAMSUNG J7MAX",
    models: ["SAMSUNG J7MAX"],
  },
  {
    mainModel: "SAMSUNG J8",
    models: ["SAMSUNG J8"],
  },
  {
    mainModel: "SAMSUNG J4PLUS",
    models: ["SAMSUNG J4PLUS", "SAMSUNG J6PLUS"],
  },
  {
    mainModel: "SAMSUNG A718",
    models: ["SAMSUNG A718"],
  },
  {
    mainModel: "SMASUNG J7",
    models: ["SAMSUNG J7"],
  },
  {
    mainModel: "VIVO V9",
    models: ["VIVO V9", "VIVO Y85", "OPPO F7", "OPPO A3", "ONEPLUS 6"],
  },
  {
    mainModel: "MI NOTE6PRO",
    models: ["MI NOTE6PRO"],
  },
  {
    mainModel: "ONEPLUS NORDCE3LITE",
    models: [
      "OBNEPLUS NORDCE3LITE",
      "REALME P3X",
      "REALME 11",
      "REALME 11X",
      "REALME 12X",
      "OPPO K12X",
      "REALME 13",
      "REALME 14X",
      "REALME C55",
      "REALME C63",
      "REALME C65",
      "RELAME C67",
      "REALME C75",
      "REALME NARZON55",
      "REALME NARZON65",
      "RELAME NARZO60X",
      "OPPO A15G",
      "OPPO A25G",
      "OPPO A35G",
      "OPPO A3X",
      "OPPO A3PRO",
      "OPPO A5PRO",
      "OPPO A58",
      "OPPO A79",
      "OPPO F23",
      "VIVO T3X",
      "VIVO T4X",
      "VIVO Y19S",
      "VIVO Y28",
      "VIVO Y29",
      "VIVO Y38",
      "VIVO Y39",
      "VIVO Y58",
      "VIVO Y200I",
      "VIVO Y200PLUS",
      "VIVO Y300I",
      "VIVO Y300T",
      "IQOO Z9X",
      "MOTO G05",
      "MOTO G15",
      "MOTO G15POWER",
      "MOTO E15",
      "MOTO G35",
      "REALME 13",
      "REALME NARZO70X",
    ],
  },
  {
    mainModel: "ONEPLUS 10R",
    models: [
      "REALME GT2PRO",
      "REALME GTNEO3",
      "OPPO F25PRO",
      "OPPO RENO8PRO",
      "OPPO RENO8PROPLUS",
      "ONEPLUS 10R",
      "ONEPLUS 10T",
      "MI 12T",
      "MI 12TPRO",
      "POCO F5PRO",
      "OPPO RENO 11F",
    ],
  },
  {
    mainModel: "NOTHNG 2",
    models: ["NOTHING 2"],
  },
  {
    mainModel: "NOTHING 2A",
    models: ["NOTHING 2A"],
  },
  {
    mainModel: "MI NOTE12PRO",
    models: [
      "SAMSUNG F54",
      "SAMSUNG M54",
      "VIVO Y36",
      "VIVO Y78",
      "SAMSUNG M53",
      "SAMSUNG M52",
      "SAMSUNG A73",
      "SMASUNG M51",
      "SAMSUNG M62",
      "SAMSUNG F62",
      "SAMSUNG A71",
      "SAMSUNG NOTE10LITE",
      "MI NOTE12PRO",
      "SMASUNG A81",
      "SAMSUNG A91",
      "POCO X5",
    ],
  },
  {
    mainModel: "VIVO V7PLUS",
    models: ["VIVO V7PLUS", "VIVO Y79"],
  },
  {
    mainModel: "VIVO V7",
    models: ["VIVO V7"],
  },
  {
    mainModel: "MI 10POWER",
    models: [
      "MI 10C",
      "MI 10POWER",
      "MI 12C",
      "MI A3",
      "MI A3X",
      "POCO C40",
      "POCO C55",
      "POCO C51",
    ],
  },
  {
    mainModel: "MI 6PRO",
    models: ["MI 6PRO", "MI A2LITE", "MI 6PLUS"],
  },
  {
    mainModel: "SAMSUNG J4",
    models: ["SAMSUNG J4"],
  },
  {
    mainModel: "MI 6A",
    models: ["MI 6A", "MI 7A"],
  },
  {
    mainModel: "MI 5",
    models: ["MI 5"],
  },
  {
    mainModel: "GOOGLE PIXEL6",
    models: ["GOOGLE PIXEL6"],
  },
  {
    mainModel: "SAMSUNG S23FE",
    models: ["SAMSUNG S23FE", "SAMSUNG A54"],
  },
  {
    mainModel: "SAMSUNG S22",
    models: ["SAMSUNG S22", "SAMSUNG S23"],
  },
  {
    mainModel: "SAMSUNG S24",
    models: ["SMAMSUNG S24"],
  },
  {
    mainModel: "SMASNUNG S24ULTRA",
    models: ["SMASUNG S24ULTRA"],
  },
  {
    mainModel: "MI NOTE 13PRO",
    models: [
      "MI NOTE13PRO",
      "POCO X6",
      "POCO X6PRO",
      "POCO F6",
      "MI NOTE13",
      "POCO F5",
      "MI NOTE12TURBO",
    ],
  },
  {
    mainModel: "GOOGLE PIXEL7",
    models: ["GOOGLE PIXEL7"],
  },
  {
    mainModel: "GOOGLE PIXEL7A",
    models: ["GOOGLE PIXEL7A"],
  },
  {
    mainModel: "GOOGLE PIXEL8A",
    models: ["GOOGLE PIXEL8A"],
  },
  {
    mainModel: "NOTHING CMF1",
    models: ["NOTHING CMF1", "NOTHING CMF2", "PIXEL 8PRO"],
  },
  {
    mainModel: "IPHONE 6",
    models: ["IPHONE 6", "IPHONE 6S"],
  },
  {
    mainModel: "MI K50I",
    models: [
      "MI NOTE11TPRO",
      "MI NOTE11TPROPLUS",
      "MI K50I",
      "POCO X4GT",
      "MI NOTE12TPRO",
    ],
  },
  {
    mainModel: "SAMSUNG M35",
    models: ["SAMSUNG M35", "SAMSUNG A35", "SAMSUNG A55"],
  },
  {
    mainModel: "MI NOTE14",
    models: [
      "MI 13T",
      "POCOC F5PRO",
      "MI K50",
      "OPPO RENO8PRO",
      "OPPO RENO8PROPLUS",
      "ONEPLUS 10T",
      "ONEPLUS 10R",
      "ONEPLUS 9RT",
      "MI 12TPRO",
      "REALME GTNEO2",
      "REALME GTNEO3",
      "REALME GT2PRO",
      "ONEPLUS NORDCE3",
      "MI NOTE14",
      "REALME GT2",
      "REALME GTNEO3T",
    ],
  },
  {
    mainModel: "MI 13",
    models: [
      "MI 12",
      "MI 13",
      "MI NOTE12R",
      "MI NOTE13R",
      "POCO M64G",
      "POCO M6PRO",
    ],
  },
  {
    mainModel: "SAMSUNG S21PLUS",
    models: ["SAMSUNG S21PLUS"],
  },
  {
    mainModel: "OPPO F5",
    models: ["OPPO F5", "REALME 1"],
  },
  {
    mainModel: "SAMSUNG A36",
    models: ["SAMSUNG A36", "SAMSUNG A56", "SAMSUNG S24FE"],
  },
  {
    mainModel: "SAMSUNG S21",
    models: ["SAMSUNG S21"],
  },
  {
    mainModel: "GOOGLE PIXEL8",
    models: ["GOOGLE PIXEL8"],
  },
  {
    mainModel: "SAMSUNG M15",
    models: [
      "SAMSUNG A15",
      "SAMSUNG A244G",
      "SAMSUNG A25",
      "SAMSUNG F15",
      "SAMSUNG F34",
      "SAMSUNG M15",
      "SAMSUNG M345G",
    ],
  },
  {
    mainModel: "POCO F1",
    models: ["POCO F1"],
  },
  {
    mainModel: "SAMSUNG S22PLUS",
    models: ["SAMSUNG S22PLUS", "SAMSUNG S23PLUS"],
  },
  {
    mainModel: "ONEPLUS 6T",
    models: ["REALME XT", "REALME X2", "OPPO K1", "ONEPLUS 6T", "ONEPLUS 7"],
  },
  {
    mainModel: "MI 14C",
    models: ["MI 14C", "MI A3PRO", "MI A4", "POCO C75", "POCO M7", "MI 14R"],
  },
  {
    mainModel: "MI 13C",
    models: [
      "RELME N61",
      "SAMSUNG M05",
      "SAMSUNG A06",
      "REALME C634G",
      "SAMSUNG M144G",
      "POCO M65G",
      "POCO C65",
      "REALME C51",
      "REALME C53",
      "SAMSUNG A05",
      " SAMSUNG A05S",
      "MI 13C",
      "REALME NARZON53",
      "REALME C61",
      "REALME NARZON63",
      "MI 13R",
      "REALME NARZON61",
    ],
  },
  {
    mainModel: "SAMSUNG A21",
    models: ["SMASUNG A21", "SAMSUNG A21S", "SAMSUNG F525G"],
  },
  {
    mainModel: "SAMSUNG A35",
    models: ["SAMSUNG A55", "SAMSUNG A35"],
  },
  {
    mainModel: "OPPO RENO13",
    models: ["OPPO RENO13"],
  },
  {
    mainModel: "SAMSUNG A26",
    models: ["SAMSUNG A16", "SAMSUNG A26"],
  },
  {
    mainModel: "NOTHING 1",
    models: ["NOTHING 1"],
  },
  {
    mainModel: "SAMSUNG S24PLUS",
    models: ["SAMSUNG S24PLUS"],
  },
  {
    mainModel: "NOTHING 3A",
    models: ["NOTHING 3A", "NOTHING 3APRO"],
  },
  {
    mainModel: "OPPO FINDX8",
    models: ["OPPO FINDX8"],
  },
  {
    mainModel: "VIVO Y200",
    models: [
      "VIVO Y200",
      "VIVO V29E",
      "POCO F5",
      "POCO X5PRO",
      "IQOO 7",
      "IQOO NEO5",
      "IQOO NEO5S",
      "IQOO NEO6",
      "IQOO NEO6SE",
      "VIVO V27E",
    ],
  },
  {
    mainModel: "POCO C71",
    models: ["POCO C71", "MI A5"],
  },
  {
    mainModel: "POCO X7PRO",
    models: ["POCOC X7PRO"],
  },
  {
    mainModel: "MI 11LITE",
    models: [
      "MI 11LITE",
      "OPPO RENO2",
      "OPPO A72",
      "OPPO A92",
      "REALME 6",
      "REALME 7",
      "REALME 6I",
      "REALME X7PRO",
      "REALME NARZO20PRO",
      "REALME NARZO30PRO",
      "ONEPLUS 8T",
      "ONEPLUS 9",
      "ONEPLUS 9R",
      "MI 12LITE",
    ],
  },
  {
    mainModel: "IQOO 12",
    models: [
      "IQOO NEO7",
      "IQOO NEO7SE",
      "IQOO NEO7PRO",
      "IQOO NEO8",
      "IQOO NEO8PRO",
      "IQOO 9",
      "IQOO 10",
      "IQOO 11",
      "IQOO1S",
      "IQOO 12",
      "IQOO Z9",
      "IQOOZ9TURBO",
    ],
  },
  {
    mainModel: "IQOO 13",
    models: ["IQOO 13"],
  },
  {
    mainModel: "IQOO NEO10",
    models: ["IQOO NEO10"],
  },
  {
    mainModel: "PIXEL 9",
    models: ["PIXEL9", "PIXEL 9PRO"],
  },
  {
    mainModel: "PIXEL 9A",
    models: ["PIXEL 9A"],
  },
  {
    mainModel: "MOTO GT30PRO",
    models: ["MOTO GT30PRO"],
  },
  {
    mainModel: "SMASUNG S25",
    models: ["SMASUNG S25"],
  },
  {
    mainModel: "SAMSUNG S25ULTRA",
    models: ["SAMSUNG S25ULTRA"],
  },
  {
    mainModel: " SAMSUNG S25PLUS",
    models: ["SAMSUNG S25PLUS"],
  },
  {
    mainModel: "SAMSUNG S25FE",
    models: ["SMASUNG S25FE"],
  },
  {
    mainModel: "SAMSUNG M56",
    models: ["SAMSUNG M56"],
  },
  {
    mainModel: "ONEPLUS 13T",
    models: ["ONEPLUS 13T"],
  },
  {
    mainModel: "ONEPLUS 13R",
    models: ["ONEPLUS 13R", "REALME NEO7"],
  },
  {
    mainModel: "IPHONE 14PROMAX",
    models: ["IPHONE 14PROMAX"],
  },
  {
    mainModel: "IPHONE 16PRO",
    models: ["IPHONE 16PRO"],
  },
  {
    mainModel: "IPHONE16PROMAX",
    models: ["IPHONE 16PROMAX"],
  },
  {
    mainModel: "MOTO EDGE60STYLUS",
    models: ["MOTO EDGE60STYLUS"],
  },
  {
    mainModel: "MOTO G84",
    models: [
      "MOTO G84",
      "VIVO V50",
      "VIVO X60",
      "VIVO X70",
      "IQOO 5",
      "IQOO 8",
      "OPPO RENO7PRO",
      "MI 11LITE",
    ],
  },
  {
    mainModel: "MOTTO G04",
    models: ["MOTTO G04", "MOTTO G24", "MOTTO G24POWER"],
  },
  {
    mainModel: "MOTTO G60",
    models: ["MOTTO G60", "MOTTO G60S", "MOTTO G51", "MOTTO G40FUSION"],
  },
  {
    mainModel: "MOTTO G52",
    models: [
      "MOTTO G52",
      "MOTTO G82",
      "MOTTO G71S",
      "MOTTO G72",
      "MOTTO EDGE30",
    ],
  },
  {
    mainModel: "MOTTO EDGE50NEO",
    models: ["MOTTO EDGE50NEO"],
  },
  {
    mainModel: "MOTTO G13",
    models: [
      "MOTTO G13",
      "MOTTO G14",
      "MOTTO G23",
      "MOTTO G32",
      "MOTTO G34",
      "MOTTO G45",
      "MOTTO G53",
      "MOTTO G54",
      "MOTTO G55",
      "MOTTO G62",
      "MOTTO G64",
      "MOTTO G73",
    ],
  },
  {
    mainModel: "MOTTO G31",
    models: ["MOTTO G31", "MOTTO G41", "MOTTO G42", "MOTTO G71"],
  },
  {
    mainModel: "MOTTO G35",
    models: ["MOTTO G35"],
  },
  {
    mainModel: "VIVO Y39",
    models: ["VIVO Y39"],
  },
  {
    mainModel: "VIVO Y19S",
    models: ["VIVO Y19S"],
  },
  {
    mainModel: "VIVO Y19E",
    models: ["VIVO Y19E"],
  },
  {
    mainModel: "OPPO F3",
    models: ["OPPO F3"],
  },
  {
    mainModel: "OPPO K13",
    models: ["OPPO K13"],
  },
  {
    mainModel: "OPPO RENO14",
    models: ["OPPO RENO14"],
  },
  {
    mainModel: "OPPO F29",
    models: ["OPPO F29"],
  },
  {
    mainModel: "REALME GT7",
    models: ["REALME NEO7", "RELAME GT7", "REALME GT7T"],
  },
  {
    mainModel: "OPPO A5PRO",
    models: ["OPPO A5PRO"],
  },
  {
    mainModel: "REALME 14X",
    models: ["REALME 14X"],
  },
  {
    mainModel: "REALME 14T",
    models: ["REALME 14T"],
  },
  {
    mainModel: "REALME 14PRO",
    models: ["REALME 14PRO"],
  },
  {
    mainModel: "OPPO RENO14PRO",
    models: ["OPPO RENO14PRO"],
  },
  {
    mainModel: "SAMSUNG M36",
    models: ["SAMSUNG M36"],
  },
  {
    mainModel: "VIVO X200FE",
    models: ["VIVO X200FE"],
  },
  {
    mainModel: "POCO F7",
    models: ["POCO F7"],
  },
  {
    mainModel: "NOTHING 3",
    models: ["NOTHING 3"],
  },
  {
    mainModel: "OPPO K13X",
    models: ["OPPIO K13X", " OPPO A5X"],
  },
  {
    mainModel: "ONEPLUS NORD5",
    models: ["ONEPLUS NORD5"],
  },
  {
    mainModel: "ONEPLUS NORDCE5",
    models: ["ONEPLUS NORDCE5"],
  },
  {
    mainModel: "SAMSUNG A225G",
    models: ["SAMSUNG A225G", "SAMSUNG F225G"],
  },
  {
    mainModel: "SAMSUG A70",
    models: ["SAMSUNG A70", "SAMSUNG A70S", "SAMSUMG A42", "SAMSUNG M42"],
  },
  {
    mainModel: "SAMSUNG A20S",
    models: ["SAMSUNG A20S","MI 9PRIME","POCO M2"],
  },
  {
    mainModel: "SAMSUNG A2CORE",
    models: ["SAMSUNG A2CORE", "J2CORE"],
  },
  {
    mainModel: "SAMSUNG J6",
    models: ["SAMSUNG J6","SAMSUNG A6"]
  },
  {
    mainModel: "MI 9A",
    models: ["MI 9A"]
  },
  {
    mainModel: "IPHONE 12MINI",
    models: ["IPHONE 12MINI"]
  },
];
