const designImages = {
  ANIME: [
    "images/AE=1.jpg",
    "images/AE=2.jpg",
    "images/AE=3.jpg",
    "images/AE=4.jpg",
    "images/AE=5.jpg",
    "images/AE=7.jpg",
  ],
  PINTRESTY: [
    "images/P=1.jpg",
    "images/P=2.jpg",
    "images/P=3.jpg",
    "images/P=4.jpg",
    "images/P=5.jpg",
    "images/P=6.jpg",
    "images/P=7.jpg",
    "images/P=8.jpg",
    "images/P=9.jpg",
    "images/P=10.jpg",
    "images/P=11.jpg",
    "images/P=12.jpg",
    "images/P=13.jpg",
    "images/P=14.jpg",
    "images/P=15.jpg",
    "images/P=16.jpg",
    "images/P=17.jpg",
    "images/P=18.jpg",
    "images/P=19.jpg",
    "images/P=20.jpg",
    "images/P=21.jpg",
    "images/P=22.jpg",
    "images/P=23.jpg",
    "images/P=24.jpg",
    "images/P=25.jpg",
    "images/P=26.jpg",
    "images/P=27.jpg",
    "images/P=28.jpg",
    "images/P=29.jpg",
    "images/P=30.jpg",
    "images/P=31.jpg",
    "images/P=32.jpg",
    "images/P=34.jpg",
    "images/P=35.jpg",
    "images/P=36.jpg",
    "images/P=37.jpg",
  ],
  "SOFT QUOTES": [
    "images/SQ=1.jpg",
    "images/SQ=2.jpg",
    "images/SQ=3.jpg",
    "images/SQ=4.jpg",
    "images/SQ=5.jpg",
    "images/SQ=6.jpg",
    "images/SQ=7.jpg",
    "images/SQ=8.jpg",
    "images/SQ=9.jpg",
  ],
  "HARD QUOTES": [
    "images/HQ=1.jpg",
    "images/HQ=2.jpg",
  ],
  "SPORTS PLAYERS": [
    "images/SP=1.jpg",
    "images/SP=2.jpg",
    "images/SP=3.jpg",
    "images/SP=4.jpg",
    "images/SP=5.jpg",
    "images/SP=6.jpg",
    "images/SP=7.jpg",
    "images/SP=8.jpg",
    "images/SP=9.jpg",
    "images/SP=10.jpg",
    "images/SP=11.jpg",
    "images/SP=12.jpg",
    "images/SP=13.jpg",
    "images/SP=14.jpg",
    "images/SP=15.jpg",
    "images/SP=16.jpg",
    "images/SP=17.jpg",
    "images/SP=18.jpg",
    "images/SP=19.jpg",
  ],
  SPORTS: [
    "images/S=1.jpg",
    "images/S=2.jpg",
    "images/S=3.jpg",
    "images/S=4.jpg",
    "images/S=5.jpg",
    "images/S=6.jpg",
    "images/S=7.jpg",
    "images/S=8.jpg",
  ],
  SCENERY: [
    "images/SY=1.jpg",
    "images/SY=2.jpg",
    "images/SY=3.jpg",
    "images/SY=4.jpg",
    "images/SY=5.jpg",
  ],
  CARS: [
    "images/C=1.jpg",
    "images/C=2.jpg",
    "images/C=3.jpg",
    "images/C=4.jpg",
    "images/C=5.jpg",
    "images/C=6.jpg",
    "images/C=7.jpg",
    "images/C=8.jpg",
    "images/C=9.jpg",
    "images/C=10.jpg",
    "images/C=11.jpg",
    "images/C=12.jpg",
    "images/C=13.jpg",
    "images/C=14.jpg",
    "images/C=15.jpg",
    "images/C=16.jpg",
    "images/C=17.jpg",
    "images/C=18.jpg",
    "images/C=19.jpg",
    "images/C=20.jpg",
    "images/C=21.jpg",
    "images/C=22.jpg",
    "images/C=23.jpg",
    "images/C=24.jpg",
    "images/C=25.jpg",
    "images/C=26.jpg",
    "images/C=27.jpg",
    "images/C=28.jpg",
    "images/C=29.jpg",
    "images/C=30.jpg",
    "images/C=31.jpg",
    "images/C=32.jpg",
    "images/C=33.jpg",
    "images/C=34.jpg",
    "images/C=35.jpg",
    "images/C=36.jpg",
    "images/C=37.jpg",
    "images/C=38.jpg",
    "images/C=39.jpg",
  ],
  "ALL MIX=1": [
    "images/AM1=1.jpg",
    "images/AM1=2.jpg",
    "images/AM1=3.jpg",
    "images/AM1=4.jpg",
    "images/AM1=5.jpg",
    "images/AM1=6.jpg",
    "images/AM1=7.jpg",
    "images/AM1=8.jpg",
    "images/AM1=9.jpg",
    "images/AM1=10.jpg",
    "images/AM1=11.jpg",
    "images/AM1=12.jpg",
    "images/AM1=13.jpg",
    "images/AM1=14.jpg",
    "images/AM1=15.jpg",
    "images/AM1=16.jpg",
    "images/AM1=17.jpg",
    "images/AM1=18.jpg",
    "images/AM1=19.jpg",
    "images/AM1=20.jpg",
    "images/AM1=21.jpg",
    "images/AM1=22.jpg",
    "images/AM1=23.jpg",
    "images/AM1=24.jpg",
  ],
  "ALL MIX=2": [
    "images/AM2=1.jpg",
    "images/AM2=2.jpg",
    "images/AM2=3.jpg",
    "images/AM2=4.jpg",
    "images/AM2=5.jpg",
    "images/AM2=6.jpg",
    "images/AM2=7.jpg",
    "images/AM2=8.jpg",
    "images/AM2=9.jpg",
    "images/AM2=10.jpg",
    "images/AM2=11.jpg",
    "images/AM2=12.jpg",
    "images/AM2=13.jpg",
    "images/AM2=14.jpg",
    "images/AM2=15.jpg",
    "images/AM2=16.jpg",
    "images/AM2=17.jpg",
    "images/AM2=18.jpg",
    "images/AM2=19.jpg",
    "images/AM2=20.jpg",
    "images/AM2=21.jpg",
    "images/AM2=22.jpg",
    "images/AM2=23.jpg",
    "images/AM2=24.jpg",
    "images/AM2=25.jpg",
    "images/AM2=26.jpg",
    "images/AM2=27.jpg",
    "images/AM2=28.jpg",
    "images/AM2=29.jpg",
    "images/AM2=30.jpg",
    "images/AM2=31.jpg",
    "images/AM2=32.jpg",
    "images/AM2=33.jpg",
    "images/AM2=34.jpg",
    "images/AM2=35.jpg",
    "images/AM2=36.jpg",
    "images/AM2=37.jpg",
    "images/AM2=38.jpg",
    "images/AM2=39.jpg",
    "images/AM2=40.jpg",
    "images/AM2=41.jpg",
    "images/AM2=42.jpg",
    "images/AM2=43.jpg",
    "images/AM2=44.jpg",
    "images/AM2=45.jpg",
    "images/AM2=46.jpg",
    "images/AM2=47.jpg",
    "images/AM2=48.jpg",
    "images/AM2=49.jpg",
    "images/AM2=50.jpg",
    "images/AM2=51.jpg",
    "images/AM2=52.jpg",
    "images/AM2=53.jpg",
    "images/AM2=54.jpg",
    "images/AM2=55.jpg",
    "images/AM2=56.jpg",
    "images/AM2=57.jpg",
    "images/AM2=58.jpg",
    "images/AM2=59.jpg",
    "images/AM2=60.jpg",
    "images/AM2=61.jpg",
    "images/AM2=62.jpg",
    "images/AM2=63.jpg",
    "images/AM2=64.jpg",
    "images/AM2=65.jpg",
    "images/AM2=66.jpg",
    "images/AM2=67.jpg",
    "images/AM2=68.jpg",
    "images/AM2=69.jpg",
    "images/AM2=70.jpg",
    "images/AM2=71.jpg",
    "images/AM2=72.jpg",
    "images/AM2=73.jpg",
    "images/AM2=74.jpg",
  ],
  LUXURY: [],
  ACTORS: [
    "images/A=1.jpg",
    "images/A=2.jpg",
    "images/A=3.jpg",
    "images/A=4.jpg",
  ],
};
// All accessories data (Airdopes + Neckbands etc.)
const accessoriesData = {
  airdopes: [
    {
      model: "Boat Airdopes 138",
      mainImage: "images/boatairdopes138=1.png",
      gallery: [
        "images/boatairdopes138=1.png",
        "images/boatairdopes138=2.jpg",
        "images/boatairdopes138=3.jpg",
        "images/boatairdopes138=4.jpg",
        "images/boatairdopes138=5.jpg",
      ],
      details: "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange guarantee (terms and conditions applied)."
    },
    {
      model: "Boat Airdopes 101v2 (black)",
      mainImage: "images/boatairdopes101v2(black)=1.png",
      gallery: [
        "images/boatairdopes101v2(black)=1.png",
        "images/boatairdopes101v2(black)=2.png",
        "images/boatairdopes101v2(black)=3.png",
        "images/boatairdopes101v2(black)=4.png",
        "images/boatairdopes101v2(black)=5.png",
        "images/boatairdopes101v2(black)=6.png",
        "images/boatairdopes101v2(black)=7.png",
        "images/boatairdopes101v2(black)=8.png",
      ],
      details: "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange guarantee (terms and conditions applied)."
    },
    {
            model: "Boat Airdopes 101v2 (white)",
            mainImage: "images/boatairdopes101v2(white)=1.png",
            gallery: [
              "images/boatairdopes101v2(white)=1.png",
              "images/boatairdopes101v2(white)=2.png",
              "images/boatairdopes101v2(white)=3.png",
              "images/boatairdopes101v2(white)=4.png",
              "images/boatairdopes101v2(white)=5.png",
              "images/boatairdopes101v2(white)=6.png",
              "images/boatairdopes101v2(white)=7.png",
              "images/boatairdopes101v2(white)=8.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 71 (black)",
            mainImage: "images/boatairdopes71(black)=1.png",
            gallery: [
              "images/boatairdopes71(black)=1.png",
              "images/boatairdopes71(black)=2.jpg",
              "images/boatairdopes71(black)=3.jpg",
              "images/boatairdopes71(black)=4.jpg",
              "images/boatairdopes71(black)=5.jpg",
              "images/boatairdopes71(black)=6.jpg",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 71 (white)",
            mainImage: "images/boatairdopes71(white)=1.png",
            gallery: [
              "images/boatairdopes71(white)=1.png",
              "images/boatairdopes71(white)=2.jpg",
              "images/boatairdopes71(white)=3.jpg",
              "images/boatairdopes71(white)=4.jpg",
              "images/boatairdopes71(white)=5.jpg",
              "images/boatairdopes71(white)=6.jpg",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes Primo",
            mainImage: "images/boatairdopesprimo=1.png",
            gallery: [
              "images/boatairdopesprimo=1.png",
              "images/boatairdopesprimo=2.png",
              "images/boatairdopesprimo=3.png",
              "images/boatairdopesprimo=4.png",
              "images/boatairdopesprimo=5.png",
              "images/boatairdopesprimo=6.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 213",
            mainImage: "images/boatairdopes213=1.png",
            gallery: [
              "images/boatairdopes213=1.png",
              "images/boatairdopes213=2.png",
              "images/boatairdopes213=3.png",
              "images/boatairdopes213=4.png",
              "images/boatairdopes213=5.png",
              "images/boatairdopes213=6.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 148 (black)",
            mainImage: "images/boatairdopes148(black)=1.png",
            gallery: [
              "images/boatairdopes148(black)=1.png",
              "images/boatairdopes148(black)=2.jpg",
              "images/boatairdopes148(black)=3.jpg",
              "images/boatairdopes148(black)=4.jpg"
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 148 (grey)",
            mainImage: "images/boatairdopes148(grey)=1.png",
            gallery: [
              "images/boatairdopes148(grey)=1.png",
              "images/boatairdopes148(grey)=2.jpg",
              "images/boatairdopes148(grey)=3.jpg",
              "images/boatairdopes148(grey)=4.jpg",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 148 Gen2 (orange)",
            mainImage: "images/boatairdopes148gen2(orange)=1.png",
            gallery: [
              "images/boatairdopes148gen2(orange)=1.png",
              "images/boatairdopes148gen2(orange)=2.png",
              "images/boatairdopes128gen2(orange)=3.png",
              "images/boatairdopes148gen2(orange)=4.png",
              "images/boatairdopes148gen2(orange)=5.png",
              "images/boatairdopes148gen2(orange)=6.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 148 Gen2 (black)",
            mainImage: "images/boatairdopes148gen2(black)=1.png",
            gallery: [
              "images/boatairdopes148gen2(black)=1.png",
              "images/boatairdopes148gen2(black)=2.png",
              "images/boatairdopes148gen2(black)=3.png",
              "images/boatairdopes148gen2(orange)=4.png",
              "images/boatairdopes148gen2(black)=5.png",
              "images/boatairdopes148gen2(black)=6.png",
              "images/boatairdopes148gen2(black)=7.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",
          },
          {
            model: "Boat Airdopes 148 Gen2 (white)",
            mainImage: "images/boatairdopes148gen2(white)=1.png",
            gallery: [
              "images/boatairdopes148gen2(white)=1.png",
              "images/boatairdopes148gen2(white)=2.png",
              "images/boatairdopes148gen2(white)=3.png",
              "images/boatairdopes148gen2(orange)=4.png",
              "images/boatairdopes148gen2(white)=5.png",
              "images/boatairdopes148gen2(white)=6.png",
              "images/boatairdopes148gen2(white)=7.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).", 
          },
          {
            model: "Boat Airdopes 212 (orange)",
            mainImage: "images/boatairdopes212(orange)=1.jpg",
            gallery: [
              "images/boatairdopes212(orange)=1.jpg",
              "images/boatairdopes212(orange)=2.jpg",
              "images/boatairdopes212(orange)=3.jpg",
              "images/boatairdopes212(orange)=4.jpg",
              "images/boatairdopes212(orange)=5.jpg",
              "images/boatairdopes212(orange)=6.jpg",
              "images/boatairdopes212(orange)=7.jpg",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",  
          },
          {
            model: "Boat Airdopes 212 (black)",
            mainImage: "images/boatairdopes212(black)=1.jpg",
            gallery: [
              "images/boatairdopes212(black)=1.jpg",
              "images/boatairdopes212(black)=2.jpg",
              "images/boatairdopes212(black)=3.jpg",
              "images/boatairdopes212(black)=4.jpg",
              "images/boatairdopes212(black)=5.jpg",
              "images/boatairdopes212(black)=6.jpg",
              "images/boatairdopes212(black)=7.jpg",
            ],
           details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 212 (white)",
            mainImage: "images/boatairdopes212(white)=1.jpg",
            gallery: [
              "images/boatairdopes212(white)=1.jpg",
              "images/boatairdopes212(white)=2.jpg",
              "images/boatairdopes212(white)=3.jpg",
              "images/boatairdopes212(orange)=4.jpg",
              "images/boatairdopes212(white)=5.jpg",
              "images/boatairdopes212(white)=6.jpg",
              "images/boatairdopes212(white)=7.jpg",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 311 Pro (black)",
            mainImage: "images/boatairdopes311pro(black)=1.png",
            gallery: [
              "images/boatairdopes311pro(black)=1.png",
              "images/boatairdopes311pro(black)=2.jpg",
              "images/boatairdopes311pro(black)=3.jpg",
              "images/boatairdopes311pro(black)=4.jpg",
              "images/boatairdopes311pro(black)=5.jpg",
              "images/boatairdopes311pro(black)=6.jpg",
              "images/boatairdopes311pro(black)=7.jpg",
              "images/boatairdopes311pro(black)=8.jpg",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes Plus 311 (black)",
            mainImage: "images/boatairdopesplus311(black)=1.png",
            gallery: [
              "images/boatairdopesplus311(black)=1.png",
              "images/boatairdopesplus311(black)=2.png",
              "images/boatairdopesplus311(black)=3.png",
              "images/boatairdopesplus311(black)=4.png",
              "images/boatairdopesplus311(black)=5.png",
              "images/boatairdopesplus311(white)=6.png",
              "images/boatairdopesplus311(black)=7.png",
              "images/boatairdopesplus311(black)=8.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes Plus 311 (white)",
            mainImage: "images/boatairdopesplus311(white)=1.png",
            gallery: [
              "images/boatairdopesplus311(white)=1.png",
              "images/boatairdopesplus311(white)=2.png",
              "images/boatairdopesplus311(white)=3.png",
              "images/boatairdopesplus311(white)=4.png",
              "images/boarairdopesplus311(white)=5.png",
              "images/boatairdopesplus311(white)=6.png",
              "images/boatairdopesplus311(white)=7.png",
              "images/boatairdopesplus311(white)=8.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 181 pro (brown)",
            mainImage: "images/boatairdopes181pro(brown)=1.png",
            gallery:
            [
              "images/boatairdopes181pro(brown)=1.png",
              "images/boatairdopes181pro(brown)=2.png",
              "images/boatairdopes181pro(brown)=3.png",
              "images/boatairdopes181pro(brown)=4.png",
              "images/boatairdopes181pro(browm)=5.png",
              "images/boatairdopes181pro(brown)=6.png",
              "images/boatairdopes181pro(brown)=7.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 121 Pro Plus (blue)",
            mainImage: "images/boatairdopes121proplus(blue)=1.png",
            gallery: [
              "images/boatairdopes121proplus(blue)=1.png",
              "images/boatairdopes121proplus(blue)=2.png",
              "images/boatairdopes121proplus(blue)=3.png",
              "images/boatairdopes121proplus(blue)=4.png",
              "images/boatairdopes121proplus(blue)=5.png",
              "images/boatairdopes121proplus(blue)=6.png",
              "images/boatairdopes121proplus(blue)=7.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 121 Pro Plus (black)",
            mainImage: "images/boatairdopes121proplus(black)=1.png",
            gallery: [
              "images/boatairdopes121proplus(black)=1.png",
              "images/boatairdopes121proplus(black)=2.png", 
              "images/boatairdopes121proplus(black)=3.png",
              "images/boatairdopes121proplus(black)=4.png",
              "images/boatairdopes121proplus(blue)=2.png",
              "images/boatairdopes121proplus(black)=6.png",
              "images/boatairdopes121proplus(black)=7.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 111v2 (black)",
            mainImage: "images/boatairdopes111v2(black)=1.png",
            gallery: [
              "images/boatairdopes111v2(black)=1.png",
              "images/boatairdopes111v2(black)=2.png",
              "images/boatairdopes111v2(black)=3.png",
              "images/boatairdopes111v2(black)=4.png",
              "images/boatairdopes111v2(black)=5.png",
              "images/boatairdopes111v2(black)=6.png",
              "images/boatairdopes111v2(black)=7.png",
              "images/boatairdopes111v2(black)=8.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 141 Elite ANC (green)",
            mainImage: "images/boatairdopes141eliteanc(green)=1.png",
            gallery: [
              "images/boatairdopes141eliteanc(green)=1.png",
              "images/boatairdopes141eliteanc(green)=2.png",
              "images/boatairdopes141eliteanc(green)=3.png",
              "images/boatairdopes141eliteanc(green)=4.png",
              "images/boatairdopes141eliteanc(green)=5.png",
              "images/boatairdopes141eliteanc(green)=6.png",
              "images/boatairdopes141eliteanc(green)=7.png",
              "images/boatairdopes141eliteanc(green)=8.png",
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 141 Elite ANC (black)",
            mainImage: "images/boatairdopes141eliteanc(black)=1.png",
            gallery: [
              "images/boatairdopes141eliteanc(black)=1.png",
              "images/boatairdopes141eliteanc(black)=2.png",
              "images/boatairdopes141eliteanc(black)=3.png",
              "images/boatairdopes141eliteanc(black)=4.png",
              "images/boatairdopes141eliteanc(black)=5.png",
              "images/boatairdopes141eliteanc(black)=6.png",
              "images/boatairdopes141eliteanc(black)=7.png",
              "images/boatairdopes141eliteanc(black)=8.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 141 Elite ANC (white)",
            mainImage: "images/boatairdopes141eliteanc(white)=1.png",
            gallery: [
              "images/boatairdopes141eliteanc(white)=1.png",
              "images/boatairdopes141eliteanc(white)=2.png",
              "images/boatairdopes141eliteanc(white)=3.png",
              "images/boatairdopes141eliteanc(white)=4.png",
              "images/boatairdopes141eliteanc(white)=5.png",
              "images/boatairdopes141eliteanc(white)=6.png",
              "images/boatairdopes141eliteanc(white)=7.png",
              "images/boatairdopes141eliteanc(white)=8.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes 161 ANC Elite (black)",
            mainImage: "images/boatairdopes161ancelite(black)=1.webp",
            gallery: [
              "images/boatairdopes161ancelite(black)=1.webp",
              "images/boatairdopes161ancelite(black)=2.webp",
              "images/boatairdopes161ancelite(black)=3.webp",
              "images/boatairdopes161ancelite(black)=4.webp",
              "images/boatairdopes161ancelite(black)=5.webp",
              "images/boatairdopes161ancelite(black)=6.webp",
              "images/boatairdopes161ancelite(black)=7.webp",
              "images/boatairdopes161ancelite(black)=8.webp",
              "images/boatairdopes161ancelite(black)=9.webp",
              "images/boatairdopes161ancelite(black)=10.webp",
              "images/boatairdopes161ancelite(black)=11.webp",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes Unity ANC (black)",
            mainImage: "images/boatairdopesunityanc(black)=1.png",
            gallery: [
              "images/boatairdopesunityanc(black)=1.png",
              "images/boatairdopesunityanc(black)=2.jpg",
              "images/boatairdopesunityanc(black)=3.jpg",
              "images/boatairdopesunityanc(black)=4.jpg",
              "images/boatairdopesunityanc(black)=5.jpg",
              "images/boatairdopesunityanc(black)=6.jpg",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",   
          },
          {
            model: "Boat Airdopes Unity ANC (white)",
            mainImage: "images/boatairdopesunityanc(white)=1.png",
            gallery: [
              "images/boatairdopesunityanc(white)=1.png",
              "images/boatairdopesunityanc(white)=2.jpg",
              "images/boatairdopesunityanc(white)=3.jpg",
              "images/boatairdopesunityanc(white)=4.jpg",
              "images/boatairdopesunityanc(white)=5.jpg",
              "images/boatairdopesunityanc(white)=6.jpg",
            ],
           details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Boat Airdopes 191 ANC (grey)",
            mainImage: "images/boatairdopes191anc(grey)=1.png",
            gallery: [
              "images/boatairdopes191anc(grey)=1.png",
              "images/boatairdopes191anc(grey)=2.png",
              "images/boatairdopes191anc(grey)=3.png",
              "images/boatairdopes191anc(grey)=4.png",
              "images/boatairdopes191anc(grey)=5.png",
              "images/boatairdopes191anc(grey)=6.png",
              "images/boatairdopes191anc(grey)=7.png",
              "images/boatairdopes191anc(grey)=8.png",
              "images/boatairdopes191anc(grey)=9.png"
            ],
            details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Boat Airdopes 191 ANC (blue)",
            mainImage: "images/boatairdopes191anc(blue)=1.png",
            gallery: [
              "images/boatairdopes191anc(blue)=1.png",
              "images/boatairdopes191anc(blue)=2.png",
              "images/boatairdopes191anc(blue)=3.png",
              "images/boatairdopes191anc(blue)=4.png",
              "images/boatairdopes191anc(blue)=5.png",
              "images/boatairdopes191anc(blue)=6.png",
              "images/boatairdopes191anc(blue)=7.png",
              "images/boatairdopes191anc(blue)=8.png",
              "images/boatairdopes191anc(blue)=9.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          }, 
          {
            model: "Boat Airdopes Loop (purple)",
            mainImage: "images/boatairdopesloop(purple)=1.png",
            gallery: [
              "images/boatairdopesloop(purple)=1.png",
              "images/boatairdopesloop(purple)=2.png",
              "images/boatairdopesloop(purple)=3.png",
              "images/boatairdopesloop(purple)=4.png",
              "images/boatairdopesloop(purple)=5.png",
              "images/boatairdopesloop(purple)=.png",
              "images/boatairdopesloop(purple)=7.png",
              "images/boatairdopesloop(purple)=8.png",
              "images/boatairdopesloop(purple)=9.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Boat Airdopes Loop (grey)",
            mainImage: "images/boatairdopesloop(grey)=1.png",
            gallery: [
              "images/boatairdopesloop(grey)=1.png",
              "images/boatairdopesloop(grey)=2.png",
              "images/boatairdopesloop(grey)=3.png",
              "images/boatairdopesloop(grey)=4.png",
              "images/boatairdopesloop(grey)=5.png",
              "images/boatairdopesloop(grey)=6.png",
              "images/boatairdopesloop(grey)=7.png",
              "images/boatairdopesloop(grey)=8.png",
              "images/boatairdopesloop(grey)=9.png",
            ],
             details:
              "Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 2r (black)",
            mainImage: "images/oneplusnordbuds2r(black)=1.webp",
            gallery: [
              "images/oneplusnordbuds2r(black)=1.webp",
              "images/oneplusnordbuds2r(black)=2.webp",
              "images/oneplusnordbuds2r(black)=3.webp",
              "images/oneplusnordbuds2r(black)=4.webp"
            ],
           details:
              "OnePlus Nord Buds 2r True Wireless in Ear Earbuds with Mic, 12.4mm Drivers, Playback:Upto 38hr case,4-Mic Design, IP55 Rating [Deep Grey]. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",     
          },
          {
            model: "Oneplus Nord Buds 2r (blue)",
            mainImage: "images/oneplusnordbuds2r(blue)=1.webp",
            gallery: [
              "images/oneplusnordbuds2r(blue)=1.webp",
              "images/oneplusnordbuds2r(blue)=2.webp",
              "images/oneplusnordbuds2r(blue)=3.webp",
              "images/oneplusnordbuds2r(blue)=3.webp",
            ],
             details:
              "OnePlus Nord Buds 2r True Wireless in Ear Earbuds with Mic, 12.4mm Drivers, Playback:Upto 38hr case,4-Mic Design, IP55 Rating [Triple Blue]. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "One Plus Nord Buds 2r (white)",
            mainImage: "images/oneplusnordbuds2r(white)=1.webp",
            gallery: [
              "images/oneplusnordbuds2r(white)=1.webp",
              "images/oneplusnordbuds2r(white)=2.webp",
              "images/oneplusnordbuds2r(white)=3.webp",
              "images/oneplusnordbuds2r(white)=4.webp",
            ],
             details:
              "OnePlus Nord Buds 2r True Wireless in Ear Earbuds with Mic, 12.4mm Drivers, Playback:Upto 38hr case,4-Mic Design, IP55 Rating [ Misty Grey ]. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 3r (black)",
            mainImage: "images/oneplusnordbuds3r(black)=1.png",
            gallery: [
              "images/oneplusnordbuds3r(black)=1.png",
              "images/oneplusnordbuds3r(black)=2.png",
              "images/oneplusnordbuds3r(black)=3.png",
              "images/oneplusnordbuds3r(black)=4.png",
              "images/oneplusnordbuds3r(black)=5.png",
              "images/oneplusnordbuds3r(black)=6.png",
              "images/oneplusnordbuds3r(black)=7.png",
            ],
            details:
              "OnePlus Nord Buds 3r TWS Earbuds up to 54 Hours Playback, 2-mic Clear Calls, 3D Spatial Audio, AI Translation, 12.4mm Drivers, Dual-Device Connectivity, 47ms Low Latency - Ash Black. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 3r (blue)",
            mainImage: "images/oneplusnordbuds3r(blue)=1.png",
            gallery: [
              "images/oneplusnordbuds3r(blue)=1.png",
              "images/oneplusnordbuds3r(blue)=2.png",
              "images/oneplusnordbuds3r(blue)=3.png",
              "images/oneplusnordbuds3r(blue)=4.png",
              "images/oneplusnordbuds3r(blue)=5.webp",
              "images/oneplusnordbuds3r(blue)=6.png",
              "images/oneplusnordbuds3r(blue)=7.png",
            ],
            details:
              "OnePlus Nord Buds 3r TWS Earbuds up to 54 Hours Playback, 2-mic Clear Calls, 3D Spatial Audio, AI Translation, 12.4mm Drivers, Dual-Device Connectivity, 47ms Low Latency - Aura Blue. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 3 (black)",
            mainImage: "images/oneplusnordbuds3(black)=1.webp",
            gallery: [
              "images/oneplusnordbuds3(black)=1.webp",
              "images/oneplusnordbuds3(black)=2.webp",
              "images/oneplusnordbuds3(black)=3.webp",
              "images/oneplusnordbuds3(black)=4.webp",
              "images/oneplusnordbuds3(black)=5.webp",
            ],
             details:
              "OnePlus Nord Buds 3 Truly Wireless Bluetooth Earbuds with up to 32dB Active Noise Cancellation, 10mins for 11Hours Fast Charging with Up to 43h Music Playback -Harmonic Gray. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "One Plus Nord Buds 3 (blue)",
            mainImage: "images/oneplusnordbuds3(blue)=1.webp",
            gallery: [
              "images/oneplusnordbuds3(blue)=1.webp",
              "images/oneplusnordbuds3(blue)=2.webp",
              "images/oneplusnordbuds3(blue)=3.webp",
              "images/oneplusnordbuds3(blue)=4.webp",
              "images/oneplusnordbuds3(blue)=5.webp",
            ],
             details:
              "OnePlus Nord Buds 3 Truly Wireless Bluetooth Earbuds with up to 32dB Active Noise Cancellation, 10mins for 11Hours Fast Charging with Up to 43h Music Playback -Chromatic Blue. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "One Plus Nord Buds 3 (white)",
            mainImage: "images/oneplusnordbuds3(white)=1.webp",
            gallery: [
              "images/oneplusnordbuds3(white)=1.webp",
              "images/oneplusnordbuds3(white)=2.webp",
              "images/oneplusnordbuds3(white)=3.webp",
              "images/oneplusnordbuds3(white)=4.webp",
              "images/oneplusnordbuds3(white)=5.webp",
            ],
            details:
              "OnePlus Nord Buds 3 Truly Wireless Bluetooth Earbuds with up to 32dB Active Noise Cancellation, 10mins for 11Hours Fast Charging with Up to 43h Music Playback -Melodic White. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 3 Pro (black)",
            mainImage: "images/oneplusnordbuds3pro(black)=1.png",
            gallery: [
              "images/oneplusnordbuds3pro(black)=1.png",
              "images/oneplusnordbuds3pro(black)=2.png",
              "images/oneplusnordbuds3pro(black)=3.png",
              "images/oneplusnordbuds3pro(black)=4.png",
              "images/oneplusnordbuds3pro(black)=5.png",
              "images/oneplusnordbuds3pro(black)=6.png",
            ],
             details:
              "OnePlus Nord Buds 3 Pro Truly Wireless Bluetooth Earbuds with Upto 49dB Active Noise Cancellation,12.4mm Dynamic Drivers,10mins for 11Hrs Fast Charging with Upto 44Hrs Music Playback [Starry Black]. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
          {
            model: "Oneplus Nord Buds 3 Pro (blue)",
            mainImage: "images/oneplusnordbuds3pro(blue)=1.webp",
            gallery: [
              "images/oneplusnordbuds3pro(blue)=1.webp",
              "images/oneplusnordbuds3pro(blue)=2.webp",
              "images/oneplusnordbuds3pro(blue)=3.webp",
              "images/oneplusnordbuds3pro(blue)=4.webp",
              "images/oneplusnordbuds3pro(blue)=5.webp",
              "images/oneplusnordbuds3pro(blue)=6.webp",
            ],
            details:
              "OnePlus Nord Buds 3 Pro Truly Wireless Bluetooth Earbuds with Upto 49dB Active Noise Cancellation,12.4mm Dynamic Drivers,10mins for 11Hrs Fast Charging with Upto 44Hrs Music Playback [Soft Jade]. Availabe for Bulk Orders. Original product at the best price. 1 year Vibex exchange gaurante(terms and condition apllied).",    
          },
  ],

  neckbands: [
    {
      model: "Boat Rockerz Summit",
      mainImage: "images/boatrockerzsummit=1.webp",
      gallery: [
        "images/boatrockerzsummit=1.webp",
        "images/boatrockerzsummit=2.webp",
        "images/boatrockerzsummit=3.webp",
        "images/boatrockerzsummit=4.webp",
        "images/boatrockerzsummit=5.webp",
        "images/boatrockerzsummit=6.webp"
      ],
      details:
      "FLIPKART PRICE =1010/= HT CURRENT PRICE= 650/="
    },
    {
      model: "Boat Rockerz 200 (black)",
      mainImage: "images/boatrockerz200(black)=1.webp",
      gallery: [
        "images/boatrockerz200(black)=1.webp",
        "images/boatrockerz200(black)=2.webp",
        "images/boatrockerz200(black)=3.webp",
        "images/boatrockerz200(black)=4.webp",
        "images/boatrockerz200(black)=5.webp",
        "images/boatrockerz200(black)=6.webp",
        "images/boatrockerz200(black)=7.webp"
      ],
      details:
      "ONLINE PRICE= NOT AVAILABLE/= HT CURRENT PRICE= 700/=",
    },
    {
      model: "Boat Rockerz 200 (blue)",
      mainImage: "images/boatrockerz200(blue)=1.webp",
      gallery: [
        "images/boatrockerz200(blue)=1.webp",
        "images/boatrockerz200(blue)=2.webp",
        "images/boatrockerz200(blue)=3.webp",
        "images/boatrockerz200(blue)=4.webp",
        "images/boatrockerz200(blue)=5.webp",
        "images/boatrockerz200(blue)=6.webp",
        "images/boatrockerz200(blue)=7.webp"
      ],
            details:
      "ONLINE PRICE= NOT AVAILABLE/= HT CURRENT PRICE= 700/=",
    },
    {
      model: "Boat Rockerz 203 (grey)",
      mainImage: "images/boatrockerz203(grey)=1.webp",
      gallery: [
        "images/boatrockerz203(grey)=1.webp",
        "images/boatrockerz203(grey)=2.webp",
        "images/boatrockerz203(grey)=3.webp",
        "images/boatrockerz203(grey)=4.webp",
        "images/boatrockerz203(grey)=5.webp",
        "images/boatrockerz203(grey)=6.webp",
        "images/boatrockerz203(grey)=7.webp",
        "images/boatrockerz203(grey)=8.webp"
      ],
      details: 
      "AMAZON PRICE= 800/= HT CURRENT PRICE= 800/=",
    },
    {
      model: "Boat Rockerz 210 ANC (black)",
      mainImage: "images/boatrockerz210anc(black)=1.webp",
      gallery: [
        "images/boatrockerz210anc(black)=1.webp",
        "images/boatrockerz210anc(black)=2.webp",
        "images/boatrockerz210anc(black)=3.webp",
        "images/boatrockerz210anc(blaCK)=4.webp",
        "images/boatrockerz210anc(black)=5.webp",
        "images/boatrockerz210anc(black)=6.webp",
        "images/boatrockerz210anc(black)=7.webp",
        "images/boatrockerz210anc(black)=8.webp",
        "images/boatrockerz210anc(black)=9.webp",
        "images/boatrockerz210anc(black)=10.webp",
        "images/boatrockerz210anc(black)=11.webp",
        "images/boatrockerz210anc(black)=12.webp"
      ],
      details: 
      "AMAZON PRICE= 1499/= HT CURRENT PRICE= 1350/=",
    },
    {
      model: "OnePlus Bullets Wireless Z3 (black)",
      mainImage: "images/oneplusbulletswirelessz3(black)=1.webp",
      gallery: [
        "images/oneplusbulletswirelessz3(black)=1.webp",
        "images/oneplusbulletswirelessz3(black)=2.png",
        "images/oneplusbulletswirelessz3(black)=3.png",
        "images/oneplusbulletswirelessz3(black)=4.webp",
        "images/oneplusbulletswirelessz3(red)(slide)=1.jpg",
        "images/oneplusbulletswirelessz3(red)(slide)=2.jpg",
        "images/oneplusbulletswirelessz3(red)(slide)=3.jpg",
        "images/oneplusbulletswirelessz3(red)(slide)=4.jpg",
        "images/oneplusbulletswirelessz3(red)(coverpage)=1.jpg"
      ],
      details: "OnePlus Bullets Wireless Z3 in-ear neckband… (same text you already use)."
    }
    // later you will add more neckbands here
  ]

  // later you can add: powerbanks: [...], headphones: [...],
};
const accessoriesBanners = {
  boatAirdopes: [
    {
      image: "images/boatairdopes161ancelite(black)=6.webp",
      text: "Boat Airdopes Best Seller"
    },
    {
      image: "images/boatairdopes161ancelite(black)=5.webp",
      text: "Boat Airdopes 161 ANC Elite"
    },
    {
      image: "images/boatairdopes161ancelite(black)=7.webp",
      text: "Best Quality Available"
    },
    {
      image: "images/boatairdopes161ancelite(black)=8.webp",
      text: "Only @1250/="
    }
    // add more slides as you like
  ],
  // later: oneplusAirdopes, oneplusNeckbands, etc.
  oneplusAirdopes: [
    {
      image: "images/oneplusnordbuds3pro(black)=5.png",
      text: "Oneplus Airdopes Best Seller"
    },
    {
      image: "images/oneplusnordbuds3pro(black)=4.png",
      text: "Oneplus Nord Buds 3 Pro (black)"
    },
    {
      image: "images/oneplusnordbuds3pro(black)=2.png",
      text: "Best Quality Available"
    },
    {
      image: "images/oneplusnordbuds3pro(black)=2.png",
      text: "Only @2600/="
    },
  ],
};
