const designImages = {
  ANIME: [
    "images/V=A=1.jpeg",
    "images/V=A=2.jpeg",
    "images/V=A=3.jpeg",
    "images/V=A=4.jpeg",
    "images/V=A=5.jpeg",
    "images/V=A=6.jpeg",
    "images/V=A=7.jpeg",
    "images/V=A=8.jpeg",
    "images/V=A=9.jpeg",
    "images/V=A=10.jpeg",
    "images/V=A=11.jpeg",
    "images/V=A=12.jpeg",
    "images/V=A=13.jpeg",
    "images/V=A=14.jpeg",
    "images/V=A=15.jpeg",
    "images/V=A=16.jpeg",
    "images/V=A=17.jpeg",
    "images/V=A=18.jpeg",
    "images/V=A=19.jpeg",
    "images/V=A=20.jpeg",
    "images/V=A=21.jpeg",
  ],
  PINTRESTY: [
    "images/V=P=1.jpeg",
    "images/V=P=2.jpeg",
    "images/V=P=3.jpeg",
    "images/V=P=4.jpeg",
    "images/V=P=5.jpeg",
    "images/V=P=6.jpeg",
    "images/V=P=7.jpeg",
    "images/V=P=8.jpeg",
    "images/V=P=9.jpeg",
    "images/V=P=10.jpeg",
    "images/V=P=11.jpeg",
    "images/V=P=12.jpeg",
    "images/V=P=13.jpeg",
    "images/V=P=14.jpeg",
    "images/V=P=15.jpeg",
    "images/V=P=16.jpeg",
    "images/V=P=17.jpeg",
    "images/V=P=18.jpeg",
    "images/V=P=19.jpeg",
    "images/V=P=20.jpeg",
    "images/V=P=21.jpeg",
    "images/V=P=22.jpeg",
    "images/V=P=23.jpeg",
    "images/V=P=24.jpeg",
    "images/V=P=25.jpeg",
    "images/V=P=26.jpeg",
    "images/V=P=27.jpeg",
    "images/V=P=28.jpeg",
    "images/V=P=29.jpeg",
    "images/V=P=30.jpeg",
    "images/V=P=31.jpeg",
    "images/V=P=32.jpeg",
    "images/V=P=33.jpeg",
    "images/V=P=34.jpeg",
  ],
  "SOFT QUOTES": [],
  "HARD QUOTES": [],
  "SPORTS PLAYERS": [],
  SPORTS: [],
  SCENERY: [],
  CARS: [],
  "ALL MIX=1": [],
  "ALL MIX=2": [],
  LUXURY: [],
  ACTORS: [],
};
